[package]
name = "ts_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = { version = "1.3.2", features = ["bundled"] }
sqlite = { version = "0.36.1", features = ["bundled"] }
thiserror = "1.0.60"
