/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            *byte |= mask;
        } else {
            *byte &= !mask;
        }
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
}
pub type u32_ = ::aya_ebpf::cty::c_uint;
pub type u64_ = ::aya_ebpf::cty::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct minmax_sample {
    pub t: u32_,
    pub v: u32_,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct minmax {
    pub s: [minmax_sample; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bbr {
    pub min_rtt_us: u32_,
    pub min_rtt_stamp: u32_,
    pub probe_rtt_done_stamp: u32_,
    pub bw: minmax,
    pub rtt_cnt: u32_,
    pub next_rtt_delivered: u32_,
    pub cycle_mstamp: u64_,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
    pub lt_bw: u32_,
    pub lt_last_delivered: u32_,
    pub lt_last_stamp: u32_,
    pub lt_last_lost: u32_,
    pub _bitfield_align_2: [u16; 0],
    pub _bitfield_2: __BindgenBitfieldUnit<[u8; 4usize]>,
    pub prior_cwnd: u32_,
    pub full_bw: u32_,
}
impl bbr {
    #[inline]
    pub fn mode(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 3u8) as u32) }
    }
    #[inline]
    pub fn set_mode(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 3u8, val as u64)
        }
    }
    #[inline]
    pub fn prev_ca_state(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(3usize, 3u8) as u32) }
    }
    #[inline]
    pub fn set_prev_ca_state(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(3usize, 3u8, val as u64)
        }
    }
    #[inline]
    pub fn packet_conservation(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(6usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_packet_conservation(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(6usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn restore_cwnd(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(7usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_restore_cwnd(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(7usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn round_start(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(8usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_round_start(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(8usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn tso_segs_goal(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(9usize, 7u8) as u32) }
    }
    #[inline]
    pub fn set_tso_segs_goal(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(9usize, 7u8, val as u64)
        }
    }
    #[inline]
    pub fn idle_restart(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(16usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_idle_restart(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(16usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn probe_rtt_round_done(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(17usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_probe_rtt_round_done(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(17usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn unused(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(18usize, 5u8) as u32) }
    }
    #[inline]
    pub fn set_unused(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(18usize, 5u8, val as u64)
        }
    }
    #[inline]
    pub fn lt_is_sampling(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(23usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_lt_is_sampling(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(23usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn lt_rtt_cnt(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(24usize, 7u8) as u32) }
    }
    #[inline]
    pub fn set_lt_rtt_cnt(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(24usize, 7u8, val as u64)
        }
    }
    #[inline]
    pub fn lt_use_bw(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(31usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_lt_use_bw(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(31usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        mode: u32_,
        prev_ca_state: u32_,
        packet_conservation: u32_,
        restore_cwnd: u32_,
        round_start: u32_,
        tso_segs_goal: u32_,
        idle_restart: u32_,
        probe_rtt_round_done: u32_,
        unused: u32_,
        lt_is_sampling: u32_,
        lt_rtt_cnt: u32_,
        lt_use_bw: u32_,
    ) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 3u8, {
            let mode: u32 = unsafe { ::core::mem::transmute(mode) };
            mode as u64
        });
        __bindgen_bitfield_unit.set(3usize, 3u8, {
            let prev_ca_state: u32 = unsafe { ::core::mem::transmute(prev_ca_state) };
            prev_ca_state as u64
        });
        __bindgen_bitfield_unit.set(6usize, 1u8, {
            let packet_conservation: u32 = unsafe { ::core::mem::transmute(packet_conservation) };
            packet_conservation as u64
        });
        __bindgen_bitfield_unit.set(7usize, 1u8, {
            let restore_cwnd: u32 = unsafe { ::core::mem::transmute(restore_cwnd) };
            restore_cwnd as u64
        });
        __bindgen_bitfield_unit.set(8usize, 1u8, {
            let round_start: u32 = unsafe { ::core::mem::transmute(round_start) };
            round_start as u64
        });
        __bindgen_bitfield_unit.set(9usize, 7u8, {
            let tso_segs_goal: u32 = unsafe { ::core::mem::transmute(tso_segs_goal) };
            tso_segs_goal as u64
        });
        __bindgen_bitfield_unit.set(16usize, 1u8, {
            let idle_restart: u32 = unsafe { ::core::mem::transmute(idle_restart) };
            idle_restart as u64
        });
        __bindgen_bitfield_unit.set(17usize, 1u8, {
            let probe_rtt_round_done: u32 = unsafe { ::core::mem::transmute(probe_rtt_round_done) };
            probe_rtt_round_done as u64
        });
        __bindgen_bitfield_unit.set(18usize, 5u8, {
            let unused: u32 = unsafe { ::core::mem::transmute(unused) };
            unused as u64
        });
        __bindgen_bitfield_unit.set(23usize, 1u8, {
            let lt_is_sampling: u32 = unsafe { ::core::mem::transmute(lt_is_sampling) };
            lt_is_sampling as u64
        });
        __bindgen_bitfield_unit.set(24usize, 7u8, {
            let lt_rtt_cnt: u32 = unsafe { ::core::mem::transmute(lt_rtt_cnt) };
            lt_rtt_cnt as u64
        });
        __bindgen_bitfield_unit.set(31usize, 1u8, {
            let lt_use_bw: u32 = unsafe { ::core::mem::transmute(lt_use_bw) };
            lt_use_bw as u64
        });
        __bindgen_bitfield_unit
    }
    #[inline]
    pub fn pacing_gain(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_2.get(0usize, 10u8) as u32) }
    }
    #[inline]
    pub fn set_pacing_gain(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_2.set(0usize, 10u8, val as u64)
        }
    }
    #[inline]
    pub fn cwnd_gain(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_2.get(10usize, 10u8) as u32) }
    }
    #[inline]
    pub fn set_cwnd_gain(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_2.set(10usize, 10u8, val as u64)
        }
    }
    #[inline]
    pub fn full_bw_reached(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_2.get(20usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_full_bw_reached(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_2.set(20usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn full_bw_cnt(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_2.get(21usize, 2u8) as u32) }
    }
    #[inline]
    pub fn set_full_bw_cnt(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_2.set(21usize, 2u8, val as u64)
        }
    }
    #[inline]
    pub fn cycle_idx(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_2.get(23usize, 3u8) as u32) }
    }
    #[inline]
    pub fn set_cycle_idx(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_2.set(23usize, 3u8, val as u64)
        }
    }
    #[inline]
    pub fn has_seen_rtt(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_2.get(26usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_has_seen_rtt(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_2.set(26usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn unused_b(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_2.get(27usize, 5u8) as u32) }
    }
    #[inline]
    pub fn set_unused_b(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_2.set(27usize, 5u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_2(
        pacing_gain: u32_,
        cwnd_gain: u32_,
        full_bw_reached: u32_,
        full_bw_cnt: u32_,
        cycle_idx: u32_,
        has_seen_rtt: u32_,
        unused_b: u32_,
    ) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 10u8, {
            let pacing_gain: u32 = unsafe { ::core::mem::transmute(pacing_gain) };
            pacing_gain as u64
        });
        __bindgen_bitfield_unit.set(10usize, 10u8, {
            let cwnd_gain: u32 = unsafe { ::core::mem::transmute(cwnd_gain) };
            cwnd_gain as u64
        });
        __bindgen_bitfield_unit.set(20usize, 1u8, {
            let full_bw_reached: u32 = unsafe { ::core::mem::transmute(full_bw_reached) };
            full_bw_reached as u64
        });
        __bindgen_bitfield_unit.set(21usize, 2u8, {
            let full_bw_cnt: u32 = unsafe { ::core::mem::transmute(full_bw_cnt) };
            full_bw_cnt as u64
        });
        __bindgen_bitfield_unit.set(23usize, 3u8, {
            let cycle_idx: u32 = unsafe { ::core::mem::transmute(cycle_idx) };
            cycle_idx as u64
        });
        __bindgen_bitfield_unit.set(26usize, 1u8, {
            let has_seen_rtt: u32 = unsafe { ::core::mem::transmute(has_seen_rtt) };
            has_seen_rtt as u64
        });
        __bindgen_bitfield_unit.set(27usize, 5u8, {
            let unused_b: u32 = unsafe { ::core::mem::transmute(unused_b) };
            unused_b as u64
        });
        __bindgen_bitfield_unit
    }
}

