/* automatically generated by rust-bindgen 0.70.1 */
// TODO: This is ugly, can it be fixed?
#[cfg(feature = "ebpf")]
use crate::kread::read_kernel;
#[cfg(feature = "ebpf")]
use aya_ebpf::helpers::gen::bpf_ktime_get_ns;
#[cfg(feature = "ebpf")]
use kernel_read_derive::KernelRead;

#[cfg(feature = "user")]
use serde::{Deserialize, Serialize};

use crate::bindings::tcp_sock::sock;

pub type u32_ = ::aya_ebpf::cty::c_uint;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cubic {
    pub cnt: u32_,
    pub last_max_cwnd: u32_,
    pub last_cwnd: u32_,
    pub last_time: u32_,
    pub bic_origin_point: u32_,
    pub bic_K: u32_,
    pub delay_min: u32_,
    pub epoch_start: u32_,
    pub ack_cnt: u32_,
    pub tcp_cwnd: u32_,
    pub _pad: [u8; 4], // unused: u16, sample_cnt: u8, found: u8
    pub round_start: u32_,
    pub end_seq: u32_,
    pub last_ack: u32_,
    pub curr_rtt: u32_,
}

#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "user", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "ebpf", derive(KernelRead))]
#[cfg_attr(feature = "ebpf", kernel_read(ctx(sk: *const sock, cubic: *const cubic), default_src = "cubic"))]
pub struct cubic_trace_entry {
    // Shared ID
    pub time: u64,
    pub addr_v4: u64,
    pub src_v6: [u8; 16usize],
    pub dst_v6: [u8; 16usize],
    pub ports: u32,
    pub family: u16,
    // Cubic
    pub cnt: u32,
    pub last_max_cwnd: u32,
    pub last_cwnd: u32,
    pub last_time: u32,
    pub bic_origin_point: u32,
    pub bic_K: u32,
    pub delay_min: u32,
    pub epoch_start: u32,
    pub ack_cnt: u32,
    pub tcp_cwnd: u32,
    pub round_start: u32,
    pub end_seq: u32,
    pub last_ack: u32,
    pub curr_rtt: u32,
}
