/* automatically generated by rust-bindgen 0.71.1 */
use super::__u32;
pub type __u16 = ::aya_ebpf::cty::c_ushort;
pub type __be16 = __u16;
pub type __be32 = __u32;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ethhdr {
    pub h_dest: [::aya_ebpf::cty::c_uchar; 6usize],
    pub h_source: [::aya_ebpf::cty::c_uchar; 6usize],
    pub h_proto: __be16,
}

