/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            *byte |= mask;
        } else {
            *byte &= !mask;
        }
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
}
#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::core::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub mod tcp_ca_event {
    pub type Type = ::aya_ebpf::cty::c_uint;
    pub const CA_EVENT_TX_START: Type = 0;
    pub const CA_EVENT_CWND_RESTART: Type = 1;
    pub const CA_EVENT_COMPLETE_CWR: Type = 2;
    pub const CA_EVENT_LOSS: Type = 3;
    pub const CA_EVENT_ECN_NO_CE: Type = 4;
    pub const CA_EVENT_ECN_IS_CE: Type = 5;
}
pub type bool_ = bool;
pub type __s32 = ::aya_ebpf::cty::c_int;
pub type s32 = __s32;
pub type __u64 = ::aya_ebpf::cty::c_ulonglong;
pub type u64_ = __u64;
pub type __s16 = ::aya_ebpf::cty::c_short;
pub type __u16 = ::aya_ebpf::cty::c_ushort;
pub type __be16 = __u16;
pub type __u8 = ::aya_ebpf::cty::c_uchar;
pub type u8_ = __u8;
pub type __u32 = ::aya_ebpf::cty::c_uint;
pub type u32_ = __u32;
pub type __be32 = __u32;
pub type __kernel_uid32_t = ::aya_ebpf::cty::c_uint;
pub type uid_t = __kernel_uid32_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct list_head {
    pub next: *mut list_head,
    pub prev: *mut list_head,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct atomic_t {
    pub counter: ::aya_ebpf::cty::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlist_node {
    pub next: *mut hlist_node,
    pub pprev: *mut *mut hlist_node,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timer_list {
    pub entry: hlist_node,
    pub expires: ::aya_ebpf::cty::c_ulong,
    pub function: ::core::option::Option<unsafe extern "C" fn(arg1: *mut timer_list)>,
    pub flags: u32_,
}
pub type spinlock_t = spinlock;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct kuid_t {
    pub val: uid_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct spinlock {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct possible_net_t {
    pub net: *mut net,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct in6_addr {
    pub in6_u: in6_addr__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union in6_addr__bindgen_ty_1 {
    pub u6_addr8: [__u8; 16usize],
    pub u6_addr16: [__be16; 8usize],
    pub u6_addr32: [__be32; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct callback_head {
    pub next: *mut callback_head,
    pub func: ::core::option::Option<unsafe extern "C" fn(arg1: *mut callback_head)>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ack_sample {
    pub pkts_acked: u32_,
    pub rtt_us: s32,
    pub in_flight: u32_,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlist_head {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sk_buff {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sock {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tcp_congestion_ops {
    pub cong_avoid:
        ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock, arg2: u32_, arg3: u32_)>,
    pub cong_control: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut sock,
            arg2: u32_,
            arg3: ::aya_ebpf::cty::c_int,
            arg4: *const rate_sample,
        ),
    >,
    pub ssthresh: ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock) -> u32_>,
    pub set_state: ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock, arg2: u8_)>,
    pub cwnd_event:
        ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock, arg2: tcp_ca_event::Type)>,
    pub in_ack_event: ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock, arg2: u32_)>,
    pub pkts_acked:
        ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock, arg2: *const ack_sample)>,
    pub min_tso_segs: ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock) -> u32_>,
    pub undo_cwnd: ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock) -> u32_>,
    pub sndbuf_expand: ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock) -> u32_>,
    pub get_info: ::core::option::Option<
        unsafe extern "C" fn(
            arg1: *mut sock,
            arg2: u32_,
            arg3: *mut ::aya_ebpf::cty::c_int,
            arg4: *mut tcp_cc_info,
        ) -> usize,
    >,
    pub name: [::aya_ebpf::cty::c_char; 16usize],
    pub owner: *mut module,
    pub list: list_head,
    pub key: u32_,
    pub flags: u32_,
    pub init: ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock)>,
    pub release: ::core::option::Option<unsafe extern "C" fn(arg1: *mut sock)>,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 40usize]>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dst_entry {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fastopen_queue {
    pub rskq_rst_head: *mut request_sock,
    pub rskq_rst_tail: *mut request_sock,
    pub lock: spinlock_t,
    pub qlen: ::aya_ebpf::cty::c_int,
    pub max_qlen: ::aya_ebpf::cty::c_int,
    pub ctx: *mut tcp_fastopen_context,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct flowi {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug)]
pub struct ip_options {
    pub faddr: __be32,
    pub nexthop: __be32,
    pub optlen: ::aya_ebpf::cty::c_uchar,
    pub srr: ::aya_ebpf::cty::c_uchar,
    pub rr: ::aya_ebpf::cty::c_uchar,
    pub ts: ::aya_ebpf::cty::c_uchar,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub router_alert: ::aya_ebpf::cty::c_uchar,
    pub cipso: ::aya_ebpf::cty::c_uchar,
    pub __pad2: ::aya_ebpf::cty::c_uchar,
    pub __data: __IncompleteArrayField<::aya_ebpf::cty::c_uchar>,
}
impl ip_options {
    #[inline]
    pub fn is_strictroute(&self) -> ::aya_ebpf::cty::c_uchar {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_is_strictroute(&mut self, val: ::aya_ebpf::cty::c_uchar) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn srr_is_hit(&self) -> ::aya_ebpf::cty::c_uchar {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(1usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_srr_is_hit(&mut self, val: ::aya_ebpf::cty::c_uchar) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(1usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn is_changed(&self) -> ::aya_ebpf::cty::c_uchar {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(2usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_is_changed(&mut self, val: ::aya_ebpf::cty::c_uchar) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(2usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn rr_needaddr(&self) -> ::aya_ebpf::cty::c_uchar {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(3usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_rr_needaddr(&mut self, val: ::aya_ebpf::cty::c_uchar) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(3usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn ts_needtime(&self) -> ::aya_ebpf::cty::c_uchar {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(4usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_ts_needtime(&mut self, val: ::aya_ebpf::cty::c_uchar) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(4usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn ts_needaddr(&self) -> ::aya_ebpf::cty::c_uchar {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(5usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_ts_needaddr(&mut self, val: ::aya_ebpf::cty::c_uchar) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(5usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        is_strictroute: ::aya_ebpf::cty::c_uchar,
        srr_is_hit: ::aya_ebpf::cty::c_uchar,
        is_changed: ::aya_ebpf::cty::c_uchar,
        rr_needaddr: ::aya_ebpf::cty::c_uchar,
        ts_needtime: ::aya_ebpf::cty::c_uchar,
        ts_needaddr: ::aya_ebpf::cty::c_uchar,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let is_strictroute: u8 = unsafe { ::core::mem::transmute(is_strictroute) };
            is_strictroute as u64
        });
        __bindgen_bitfield_unit.set(1usize, 1u8, {
            let srr_is_hit: u8 = unsafe { ::core::mem::transmute(srr_is_hit) };
            srr_is_hit as u64
        });
        __bindgen_bitfield_unit.set(2usize, 1u8, {
            let is_changed: u8 = unsafe { ::core::mem::transmute(is_changed) };
            is_changed as u64
        });
        __bindgen_bitfield_unit.set(3usize, 1u8, {
            let rr_needaddr: u8 = unsafe { ::core::mem::transmute(rr_needaddr) };
            rr_needaddr as u64
        });
        __bindgen_bitfield_unit.set(4usize, 1u8, {
            let ts_needtime: u8 = unsafe { ::core::mem::transmute(ts_needtime) };
            ts_needtime as u64
        });
        __bindgen_bitfield_unit.set(5usize, 1u8, {
            let ts_needaddr: u8 = unsafe { ::core::mem::transmute(ts_needaddr) };
            ts_needaddr as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug)]
pub struct ip_options_rcu {
    pub rcu: callback_head,
    pub opt: ip_options,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct inet6_cork {
    pub opt: *mut ipv6_txoptions,
    pub hop_limit: u8_,
    pub tclass: u8_,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub __bindgen_padding_0: [u8; 5usize],
}
impl inet6_cork {
    #[inline]
    pub fn dontfrag(&self) -> u8_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_dontfrag(&mut self, val: u8_) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(dontfrag: u8_) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let dontfrag: u8 = unsafe { ::core::mem::transmute(dontfrag) };
            dontfrag as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct inet_bind2_bucket {
    pub ib_net: possible_net_t,
    pub l3mdev: ::aya_ebpf::cty::c_int,
    pub port: ::aya_ebpf::cty::c_ushort,
    pub addr_type: ::aya_ebpf::cty::c_ushort,
    pub v6_rcv_saddr: in6_addr,
    pub node: hlist_node,
    pub bhash_node: hlist_node,
    pub owners: hlist_head,
    pub fastreuse: ::aya_ebpf::cty::c_schar,
    pub fastreuseport: ::aya_ebpf::cty::c_schar,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct inet_bind_bucket {
    pub ib_net: possible_net_t,
    pub l3mdev: ::aya_ebpf::cty::c_int,
    pub port: ::aya_ebpf::cty::c_ushort,
    pub fastreuse: ::aya_ebpf::cty::c_schar,
    pub fastreuseport: ::aya_ebpf::cty::c_schar,
    pub fastuid: kuid_t,
    pub fast_v6_rcv_saddr: in6_addr,
    pub fast_rcv_saddr: __be32,
    pub fast_sk_family: ::aya_ebpf::cty::c_ushort,
    pub fast_ipv6_only: bool_,
    pub node: hlist_node,
    pub bhash2: hlist_head,
    pub rcu: callback_head,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct inet_cork {
    pub flags: ::aya_ebpf::cty::c_uint,
    pub addr: __be32,
    pub opt: *mut ip_options,
    pub fragsize: ::aya_ebpf::cty::c_uint,
    pub length: ::aya_ebpf::cty::c_int,
    pub dst: *mut dst_entry,
    pub tx_flags: u8_,
    pub ttl: __u8,
    pub tos: __s16,
    pub priority: u32_,
    pub gso_size: __u16,
    pub ts_opt_id: u32_,
    pub transmit_time: u64_,
    pub mark: u32_,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct inet_cork_full {
    pub base: inet_cork,
    pub fl: flowi,
    pub base6: inet6_cork,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct inet_sock {
    pub sk: sock,
    pub pinet6: *mut ipv6_pinfo,
    pub ipv6_fl_list: *mut ipv6_fl_socklist,
    pub inet_flags: ::aya_ebpf::cty::c_ulong,
    pub inet_saddr: __be32,
    pub uc_ttl: __s16,
    pub inet_sport: __be16,
    pub inet_opt: *mut ip_options_rcu,
    pub inet_id: atomic_t,
    pub tos: __u8,
    pub min_ttl: __u8,
    pub mc_ttl: __u8,
    pub pmtudisc: __u8,
    pub rcv_tos: __u8,
    pub convert_csum: __u8,
    pub uc_index: ::aya_ebpf::cty::c_int,
    pub mc_index: ::aya_ebpf::cty::c_int,
    pub mc_addr: __be32,
    pub local_port_range: u32_,
    pub mc_list: *mut ip_mc_socklist,
    pub cork: inet_cork_full,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct request_sock_queue {
    pub rskq_lock: spinlock_t,
    pub rskq_defer_accept: u8_,
    pub synflood_warned: u8_,
    pub qlen: atomic_t,
    pub young: atomic_t,
    pub rskq_accept_head: *mut request_sock,
    pub rskq_accept_tail: *mut request_sock,
    pub fastopenq: fastopen_queue,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct inet_connection_sock {
    pub icsk_inet: inet_sock,
    pub icsk_accept_queue: request_sock_queue,
    pub icsk_bind_hash: *mut inet_bind_bucket,
    pub icsk_bind2_hash: *mut inet_bind2_bucket,
    pub icsk_delack_timer: timer_list,
    pub __bindgen_anon_1: inet_connection_sock__bindgen_ty_1,
    pub icsk_rto: __u32,
    pub icsk_rto_min: __u32,
    pub icsk_rto_max: u32_,
    pub icsk_delack_max: __u32,
    pub icsk_pmtu_cookie: __u32,
    pub icsk_ca_ops: *const tcp_congestion_ops,
    pub icsk_af_ops: *const inet_connection_sock_af_ops,
    pub icsk_ulp_ops: *const tcp_ulp_ops,
    pub icsk_ulp_data: *mut ::aya_ebpf::cty::c_void,
    pub icsk_sync_mss: ::core::option::Option<
        unsafe extern "C" fn(arg1: *mut sock, arg2: u32_) -> ::aya_ebpf::cty::c_uint,
    >,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub icsk_retransmits: __u8,
    pub icsk_pending: __u8,
    pub icsk_backoff: __u8,
    pub icsk_syn_retries: __u8,
    pub icsk_probes_out: __u8,
    pub icsk_ext_hdr_len: __u16,
    pub icsk_ack: inet_connection_sock__bindgen_ty_2,
    pub icsk_mtup: inet_connection_sock__bindgen_ty_3,
    pub icsk_probes_tstamp: u32_,
    pub icsk_user_timeout: u32_,
    pub icsk_ca_priv: [u64_; 13usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union inet_connection_sock__bindgen_ty_1 {
    pub icsk_keepalive_timer: timer_list,
    pub mptcp_tout_timer: timer_list,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct inet_connection_sock__bindgen_ty_2 {
    pub pending: __u8,
    pub quick: __u8,
    pub pingpong: __u8,
    pub retry: __u8,
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
    pub lrcvtime: __u32,
    pub last_seg_size: __u16,
    pub rcv_mss: __u16,
}
impl inet_connection_sock__bindgen_ty_2 {
    #[inline]
    pub fn ato(&self) -> __u32 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 8u8) as u32) }
    }
    #[inline]
    pub fn set_ato(&mut self, val: __u32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 8u8, val as u64)
        }
    }
    #[inline]
    pub fn lrcv_flowlabel(&self) -> __u32 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(8usize, 20u8) as u32) }
    }
    #[inline]
    pub fn set_lrcv_flowlabel(&mut self, val: __u32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(8usize, 20u8, val as u64)
        }
    }
    #[inline]
    pub fn dst_quick_ack(&self) -> __u32 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(28usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_dst_quick_ack(&mut self, val: __u32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(28usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn unused(&self) -> __u32 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(29usize, 3u8) as u32) }
    }
    #[inline]
    pub fn set_unused(&mut self, val: __u32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(29usize, 3u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        ato: __u32,
        lrcv_flowlabel: __u32,
        dst_quick_ack: __u32,
        unused: __u32,
    ) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 8u8, {
            let ato: u32 = unsafe { ::core::mem::transmute(ato) };
            ato as u64
        });
        __bindgen_bitfield_unit.set(8usize, 20u8, {
            let lrcv_flowlabel: u32 = unsafe { ::core::mem::transmute(lrcv_flowlabel) };
            lrcv_flowlabel as u64
        });
        __bindgen_bitfield_unit.set(28usize, 1u8, {
            let dst_quick_ack: u32 = unsafe { ::core::mem::transmute(dst_quick_ack) };
            dst_quick_ack as u64
        });
        __bindgen_bitfield_unit.set(29usize, 3u8, {
            let unused: u32 = unsafe { ::core::mem::transmute(unused) };
            unused as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct inet_connection_sock__bindgen_ty_3 {
    pub search_high: ::aya_ebpf::cty::c_int,
    pub search_low: ::aya_ebpf::cty::c_int,
    pub _bitfield_align_1: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
    pub probe_timestamp: u32_,
}
impl inet_connection_sock__bindgen_ty_3 {
    #[inline]
    pub fn probe_size(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 31u8) as u32) }
    }
    #[inline]
    pub fn set_probe_size(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 31u8, val as u64)
        }
    }
    #[inline]
    pub fn enabled(&self) -> u32_ {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(31usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_enabled(&mut self, val: u32_) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(31usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(probe_size: u32_, enabled: u32_) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 31u8, {
            let probe_size: u32 = unsafe { ::core::mem::transmute(probe_size) };
            probe_size as u64
        });
        __bindgen_bitfield_unit.set(31usize, 1u8, {
            let enabled: u32 = unsafe { ::core::mem::transmute(enabled) };
            enabled as u64
        });
        __bindgen_bitfield_unit
    }
}
impl inet_connection_sock {
    #[inline]
    pub fn icsk_ca_state(&self) -> __u8 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 5u8) as u8) }
    }
    #[inline]
    pub fn set_icsk_ca_state(&mut self, val: __u8) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 5u8, val as u64)
        }
    }
    #[inline]
    pub fn icsk_ca_initialized(&self) -> __u8 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(5usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_icsk_ca_initialized(&mut self, val: __u8) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(5usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn icsk_ca_setsockopt(&self) -> __u8 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(6usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_icsk_ca_setsockopt(&mut self, val: __u8) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(6usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn icsk_ca_dst_locked(&self) -> __u8 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(7usize, 1u8) as u8) }
    }
    #[inline]
    pub fn set_icsk_ca_dst_locked(&mut self, val: __u8) {
        unsafe {
            let val: u8 = ::core::mem::transmute(val);
            self._bitfield_1.set(7usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        icsk_ca_state: __u8,
        icsk_ca_initialized: __u8,
        icsk_ca_setsockopt: __u8,
        icsk_ca_dst_locked: __u8,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 5u8, {
            let icsk_ca_state: u8 = unsafe { ::core::mem::transmute(icsk_ca_state) };
            icsk_ca_state as u64
        });
        __bindgen_bitfield_unit.set(5usize, 1u8, {
            let icsk_ca_initialized: u8 = unsafe { ::core::mem::transmute(icsk_ca_initialized) };
            icsk_ca_initialized as u64
        });
        __bindgen_bitfield_unit.set(6usize, 1u8, {
            let icsk_ca_setsockopt: u8 = unsafe { ::core::mem::transmute(icsk_ca_setsockopt) };
            icsk_ca_setsockopt as u64
        });
        __bindgen_bitfield_unit.set(7usize, 1u8, {
            let icsk_ca_dst_locked: u8 = unsafe { ::core::mem::transmute(icsk_ca_dst_locked) };
            icsk_ca_dst_locked as u64
        });
        __bindgen_bitfield_unit
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct inet_connection_sock_af_ops {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct request_sock {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ip_mc_socklist {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ipv6_fl_socklist {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ipv6_pinfo {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ipv6_txoptions {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct module {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct net {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rate_sample {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tcp_sock {
    pub _address: u8,
}
#[repr(C)]
#[repr(align(4))]
#[derive(Copy, Clone)]
pub union tcp_cc_info {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tcp_fastopen_context {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tcp_ulp_ops {
    pub _address: u8,
}

