#[cfg(feature = "user")]
use serde::{Deserialize, Serialize};

/* automatically generated by rust-bindgen 0.71.1 */
use super::{trace_entry, __u8, __u16, __u32, __u64, __IncompleteArrayField };

#[repr(C)]
#[derive(Debug)]
pub struct trace_event_raw_tcp_probe {
    pub ent: trace_entry,
    pub saddr: [__u8; 28usize],
    pub daddr: [__u8; 28usize],
    pub sport: __u16,
    pub dport: __u16,
    pub family: __u16,
    pub mark: __u32,
    pub data_len: __u16,
    pub snd_nxt: __u32,
    pub snd_una: __u32,
    pub snd_cwnd: __u32,
    pub ssthresh: __u32,
    pub snd_wnd: __u32,
    pub srtt: __u32,
    pub rcv_wnd: __u32,
    pub sock_cookie: __u64,
    pub __data: __IncompleteArrayField<::aya_ebpf::cty::c_char>,
}
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
#[cfg_attr(feature = "user", derive(Serialize, Deserialize))]
pub struct tcp_probe_entry {
    pub time: u64,
    pub saddr: [u8; 28usize],
    pub daddr: [u8; 28usize],
    pub sport: u16,
    pub dport: u16,
    pub family: u16,
    pub mark: u32,
    pub data_len: u16,
    pub snd_nxt: u32,
    pub snd_una: u32,
    pub snd_cwnd: u32,
    pub ssthresh: u32,
    pub snd_wnd: u32,
    pub srtt: u32,
    pub rcv_wnd: u32,
    pub sock_cookie: u64,
}