//! Ring buffer records and map keys, generated by build.rs from `tcbee/src/bpf/records.h`.
//!
//! The trace files are bincode serialised field by field, so changing a field's order or
//! type here changes the on-disk format. The size asserts catch accidental changes.
#![allow(non_camel_case_types, non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/records.rs"));

use core::mem::size_of;

const _: () = assert!(size_of::<tcp4_packet_trace>() == 40);
const _: () = assert!(size_of::<tcp6_packet_trace>() == 64);
const _: () = assert!(size_of::<sock_trace_entry>() == 184);
const _: () = assert!(size_of::<cwnd_trace_entry>() == 72);
const _: () = assert!(size_of::<cubic_trace_entry>() == 120);
const _: () = assert!(size_of::<bbr_trace_entry>() == 120);
const _: () = assert!(size_of::<tcp_probe_entry>() == 128);
const _: () = assert!(size_of::<tcp_retransmit_synack_entry>() == 64);
const _: () = assert!(size_of::<tcp_bad_csum_entry>() == 24);
const _: () = assert!(size_of::<IpTuple>() == 38);
const _: () = assert!(size_of::<hook_seq_key>() == 40);
const _: () = assert!(size_of::<FilterIp>() == 16);
