//! Ring buffer records and map keys, generated by build.rs from `tcbee/src/bpf/records.h`.
//!
//! The trace files are bincode serialised field by field, so changing a field's order or
//! type here changes the on-disk format. The size asserts catch accidental changes.
#![allow(non_camel_case_types, non_snake_case)]

#[cfg(feature = "ebpf")]
use crate::{
    bindings::{
        bbr::bbr,
        cubic::cubic,
        tcp_sock::{sock, tcp_sock},
    },
    kread::read_kernel,
};
#[cfg(feature = "ebpf")]
use aya_ebpf::helpers::generated::bpf_ktime_get_ns;

include!(concat!(env!("OUT_DIR"), "/records.rs"));

use core::mem::size_of;

const _: () = assert!(size_of::<tcp4_packet_trace>() == 32);
const _: () = assert!(size_of::<tcp6_packet_trace>() == 56);
const _: () = assert!(size_of::<sock_trace_entry>() == 176);
const _: () = assert!(size_of::<cwnd_trace_entry>() == 64);
const _: () = assert!(size_of::<cubic_trace_entry>() == 112);
const _: () = assert!(size_of::<bbr_trace_entry>() == 112);
const _: () = assert!(size_of::<tcp_probe_entry>() == 120);
const _: () = assert!(size_of::<tcp_retransmit_synack_entry>() == 56);
const _: () = assert!(size_of::<tcp_bad_csum_entry>() == 16);
const _: () = assert!(size_of::<IpTuple>() == 38);
const _: () = assert!(size_of::<FilterIp>() == 16);

impl IpTuple {
    /// Returns a canonical form with the lexicographically smaller (ip, port) pair as src,
    /// so both directions of a TCP connection map to the same hash-map key.
    #[inline(always)]
    pub fn canonical(self) -> Self {
        let swap =
            self.src_ip > self.dst_ip || (self.src_ip == self.dst_ip && self.sport > self.dport);
        if swap {
            IpTuple {
                src_ip: self.dst_ip,
                dst_ip: self.src_ip,
                sport: self.dport,
                dport: self.sport,
                protocol: self.protocol,
            }
        } else {
            self
        }
    }
}
