name: TCBee build

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y llvm clang libelf-dev libclang-dev pkg-config fontconfig libfontconfig1-dev duckdb
        cargo install bpf-linker

    - name: TCBee-Record Build
      run: cd tcbee-record && cargo build --release

    - name: TCBee-Process Build
      run: cd tcbee-process && cargo build --release

    - name: TCBee-Viz Build
      run: cd tcbee-viz && cargo build --release      