name: TCBee build

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Rust Nightly
      run: rustup toolchain install nightly --component rust-src

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y llvm clang libelf-dev libclang-dev pkg-config cmake fontconfig libfontconfig1-dev libgl-dev libegl-dev
        cargo install bpf-linker

    - name: TCBee-Record Build
      run: cd tcbee-record && cargo build --release

    - name: TCBee-Process Build
      run: cd tcbee-process && cargo build --release --features ts_storage/bundled

    - name: TCBee-Viz Build
      run: cd tcbee-viz && cargo build --release --features ts_storage/bundled

    - name: TCBee-Live Build
      run: cd tcbee-live && cargo build --release